variables:
  REGISTRY: 968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/staging

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export ts=`date +%s`
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --destination "${REGISTRY}:${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}-$ts"
      --destination "${REGISTRY}:${CI_PROJECT_PATH_SLUG}-dev-latest"
  tags:
    - build
    - k8s
  only:
    refs:
      - dev
